steps:

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - '-c'
    - |
      gcloud compute ssh bastion-vm \
      --zone=asia-south1-a \
      --tunnel-through-iap \
      --command="hostname"

options:
  logging: CLOUD_LOGGING_ONLY
